# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1z8au76uiM4lduAPGXiSUZdMhsaSiXNfI
"""

# =============================================================
#  BERT fine-tuning untuk Fake News Detection (dataset ISOT)
#  Jalankan di Google Colab / mesin ber-GPU dengan akses internet.
#  Tidak bisa dijalankan di sandbox Claude (tanpa GPU & HuggingFace diblokir).
#
#  Cara pakai di Colab:
#   1. Runtime > Change runtime type > GPU
#   2. Upload Fake.csv dan True.csv
#   3. !pip install transformers datasets scikit-learn accelerate -q
#   4. Jalankan file ini. Catat nilai accuracy/precision/recall/F1 yang dicetak,
#      lalu masukkan ke baris "BERT" pada Tabel I di paper.
# =============================================================
from  google.colab import files
import re, numpy as np, pandas as pd, torch
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix
from transformers import (AutoTokenizer, AutoModelForSequenceClassification,
                          TrainingArguments, Trainer)
from datasets import Dataset
!pip install transformers datasets scikit-learn accelerate -q

uploaded = files.upload()

MODEL_NAME = "bert-base-uncased"   # bisa diganti "distilbert-base-uncased" agar lebih cepat
MAX_LEN = 256
SEED = 42

#1. Load & preprocess (sama dengan pipeline di paper) ----
fake = pd.read_csv("Fake.csv"); fake["label"] = 1   # fake = positive class
true = pd.read_csv("True.csv"); true["label"] = 0
df = pd.concat([fake, true], ignore_index=True)
df["content"] = (df["title"].fillna("") + " " + df["text"].fillna("")).astype(str)
df = df[df["content"].str.strip().str.len() > 0].drop_duplicates(subset=["content"])

def clean(t):
    t = t.lower()
    t = re.sub(r"http\S+|www\.\S+", " ", t)
    t = re.sub(r"[^a-z\s]", " ", t)
    return re.sub(r"\s+", " ", t).strip()

df["clean"] = df["content"].apply(clean)
df = df[df["clean"].str.split().str.len() >= 5]

#2. Split 70/10/20
X, y = df["clean"].values, df["label"].values
X_tmp, X_te, y_tmp, y_te = train_test_split(X, y, test_size=0.20, stratify=y, random_state=SEED)
X_tr, X_va, y_tr, y_va = train_test_split(X_tmp, y_tmp, test_size=0.125, stratify=y_tmp, random_state=SEED)

tok = AutoTokenizer.from_pretrained(MODEL_NAME)
def to_ds(texts, labels):
    d = Dataset.from_dict({"text": list(texts), "label": list(labels)})
    return d.map(lambda b: tok(b["text"], truncation=True, padding="max_length",
                               max_length=MAX_LEN), batched=True)
ds_tr, ds_va, ds_te = to_ds(X_tr, y_tr), to_ds(X_va, y_va), to_ds(X_te, y_te)

#3. Model & training
model = AutoModelForSequenceClassification.from_pretrained(MODEL_NAME, num_labels=2)
def metrics(p):
    preds = np.argmax(p.predictions, axis=1)
    return {"accuracy": accuracy_score(p.label_ids, preds),
            "precision": precision_score(p.label_ids, preds),
            "recall": recall_score(p.label_ids, preds),
            "f1": f1_score(p.label_ids, preds)}

args = TrainingArguments(
    output_dir="bert_fnd", num_train_epochs=2, per_device_train_batch_size=16,
    per_device_eval_batch_size=32, learning_rate=2e-5, weight_decay=0.01,
    eval_strategy="epoch", save_strategy="no", logging_steps=100, seed=SEED, fp16=True)

trainer = Trainer(model=model, args=args, train_dataset=ds_tr,
                  eval_dataset=ds_va, compute_metrics=metrics)
trainer.train()

#4. Final evaluation on TEST set
pred = trainer.predict(ds_te)
y_pred = np.argmax(pred.predictions, axis=1)
print("\n===== BERT TEST RESULTS (masukkan ke Tabel I) =====")
print("Accuracy : %.2f" % (accuracy_score(y_te, y_pred) * 100))
print("Precision: %.2f" % (precision_score(y_te, y_pred) * 100))
print("Recall   : %.2f" % (recall_score(y_te, y_pred) * 100))
print("F1-score : %.2f" % (f1_score(y_te, y_pred) * 100))
print("Confusion matrix [[TN,FP],[FN,TP]]:\n", confusion_matrix(y_te, y_pred))