# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VpJeEPzoz9nTEru50x38GBLmdpJ6SRGY
"""

# FAKE NEWS DETECTION - CNN & BiLSTM

!pip install pandas numpy scikit-learn matplotlib torch -q
import pandas as pd
import numpy as np
import re
import random
import torch
import torch.nn as nn
import matplotlib.pyplot as plt
from google.colab import files


from collections import Counter
from torch.utils.data import Dataset, DataLoader
from sklearn.model_selection import train_test_split
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    classification_report
)
uploaded = files.upload()

# 2. Set Random Seed
SEED = 42

random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED)
torch.cuda.manual_seed_all(SEED)

torch.backends.cudnn.deterministic = True
torch.backends.cudnn.benchmark = False

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Device digunakan:", device)

# 3. Load Dataset
fake_df = pd.read_csv("Fake.csv")
true_df = pd.read_csv("True.csv")

fake_df["label"] = 1   # Fake news
true_df["label"] = 0   # True news

df = pd.concat([fake_df, true_df], ignore_index=True)
df["content"] = df["text"].astype(str)

# Hapus data kosong dan duplikasi
df = df.dropna(subset=["content", "label"])
df = df.drop_duplicates(subset=["content"])
df = df.sample(frac=1, random_state=SEED).reset_index(drop=True)

print("Jumlah data setelah preprocessing awal:", len(df))
print("Distribusi label:")
print(df["label"].value_counts())

texts = df["content"].astype(str).tolist()
labels = df["label"].astype(int).tolist()

# 4. Cleaning Text
def clean_text(text):
    text = text.lower()
    text = re.sub(r"http\S+|www\S+", " ", text)
    text = re.sub(r"[^a-zA-Z0-9\s]", " ", text)
    text = re.sub(r"\s+", " ", text).strip()
    return text

cleaned_texts = [clean_text(text) for text in texts]
tokenized_texts = [text.split() for text in cleaned_texts]

# 5. Build Vocabulary
MAX_VOCAB_SIZE = 20000
MAX_SEQ_LEN = 200

word_counter = Counter()

for tokens in tokenized_texts:
    word_counter.update(tokens)

most_common_words = word_counter.most_common(MAX_VOCAB_SIZE - 2)

word2idx = {
    "<PAD>": 0,
    "<OOV>": 1
}

for idx, (word, count) in enumerate(most_common_words, start=2):
    word2idx[word] = idx

vocab_size = len(word2idx)
print("Vocabulary size:", vocab_size)

def tokens_to_sequence(tokens, word2idx, max_len):
    sequence = [word2idx.get(token, word2idx["<OOV>"]) for token in tokens]

    if len(sequence) < max_len:
        sequence = sequence + [word2idx["<PAD>"]] * (max_len - len(sequence))
    else:
        sequence = sequence[:max_len]

    return sequence

sequences = [
    tokens_to_sequence(tokens, word2idx, MAX_SEQ_LEN)
    for tokens in tokenized_texts
]

# 6. Train / Validation / Test Split
# 70% train, 10% validation, 20% test

X_train, X_temp, y_train, y_temp = train_test_split(
    sequences,
    labels,
    test_size=0.30,
    random_state=SEED,
    stratify=labels
)

X_val, X_test, y_val, y_test = train_test_split(
    X_temp,
    y_temp,
    test_size=2/3,
    random_state=SEED,
    stratify=y_temp
)

print("\nJumlah data:")
print("Train      :", len(X_train))
print("Validation :", len(X_val))
print("Test       :", len(X_test))

# 7. Dataset dan DataLoader
class NewsDataset(Dataset):
    def __init__(self, X, y):
        self.X = torch.tensor(X, dtype=torch.long)
        self.y = torch.tensor(y, dtype=torch.float32)

    def __len__(self):
        return len(self.X)

    def __getitem__(self, idx):
        return self.X[idx], self.y[idx]

BATCH_SIZE = 64

train_dataset = NewsDataset(X_train, y_train)
val_dataset = NewsDataset(X_val, y_val)
test_dataset = NewsDataset(X_test, y_test)

train_loader = DataLoader(
    train_dataset,
    batch_size=BATCH_SIZE,
    shuffle=True
)

val_loader = DataLoader(
    val_dataset,
    batch_size=BATCH_SIZE,
    shuffle=False
)

test_loader = DataLoader(
    test_dataset,
    batch_size=BATCH_SIZE,
    shuffle=False
)

# 8. Model CNN

class CNNTextClassifier(nn.Module):
    def __init__(
        self,
        vocab_size,
        embed_dim=64,
        num_filters=100,
        kernel_sizes=(3, 4, 5),
        dropout=0.5
    ):
        super(CNNTextClassifier, self).__init__()

        self.embedding = nn.Embedding(
            vocab_size,
            embed_dim,
            padding_idx=0
        )

        self.convs = nn.ModuleList([
            nn.Conv2d(
                in_channels=1,
                out_channels=num_filters,
                kernel_size=(kernel_size, embed_dim)
            )
            for kernel_size in kernel_sizes
        ])

        self.dropout = nn.Dropout(dropout)
        self.fc = nn.Linear(num_filters * len(kernel_sizes), 1)

    def forward(self, x):
        x = self.embedding(x)
        x = x.unsqueeze(1)

        conv_outputs = [
            torch.relu(conv(x)).squeeze(3)
            for conv in self.convs
        ]

        pooled_outputs = [
            torch.max(conv_output, dim=2)[0]
            for conv_output in conv_outputs
        ]

        x = torch.cat(pooled_outputs, dim=1)
        x = self.dropout(x)
        x = self.fc(x)

        return x.squeeze(1)

# 9. Model BiLSTM

class BiLSTMTextClassifier(nn.Module):
    def __init__(
        self,
        vocab_size,
        embed_dim=64,
        hidden_dim=128,
        num_layers=2,
        dropout=0.5
    ):
        super(BiLSTMTextClassifier, self).__init__()

        self.embedding = nn.Embedding(
            vocab_size,
            embed_dim,
            padding_idx=0
        )

        self.lstm = nn.LSTM(
            input_size=embed_dim,
            hidden_size=hidden_dim,
            num_layers=num_layers,
            batch_first=True,
            bidirectional=True,
            dropout=dropout
        )

        self.dropout = nn.Dropout(dropout)
        self.fc = nn.Linear(hidden_dim * 2, 1)

    def forward(self, x):
        x = self.embedding(x)

        output, (hidden, cell) = self.lstm(x)

        forward_hidden = hidden[-2]
        backward_hidden = hidden[-1]

        x = torch.cat((forward_hidden, backward_hidden), dim=1)
        x = self.dropout(x)
        x = self.fc(x)

        return x.squeeze(1)

# 10. Evaluation Function

def evaluate_model(model, data_loader):
    model.eval()

    y_true = []
    y_pred = []

    with torch.no_grad():
        for X_batch, y_batch in data_loader:
            X_batch = X_batch.to(device)

            outputs = model(X_batch)
            probs = torch.sigmoid(outputs)
            preds = (probs >= 0.5).long().cpu().numpy()

            y_pred.extend(preds)
            y_true.extend(y_batch.numpy().astype(int))

    accuracy = accuracy_score(y_true, y_pred)
    precision = precision_score(y_true, y_pred, zero_division=0)
    recall = recall_score(y_true, y_pred, zero_division=0)
    f1 = f1_score(y_true, y_pred, zero_division=0)
    cm = confusion_matrix(y_true, y_pred)

    return accuracy, precision, recall, f1, cm, y_true, y_pred

# 11. Training Function

def train_model(
    model,
    model_name,
    train_loader,
    val_loader,
    epochs=5,
    learning_rate=0.001
):
    model = model.to(device)

    criterion = nn.BCEWithLogitsLoss()
    optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)

    history = {
        "train_loss": [],
        "val_accuracy": [],
        "val_precision": [],
        "val_recall": [],
        "val_f1": []
    }

    print(f"\n===== Training {model_name} =====")

    for epoch in range(1, epochs + 1):
        model.train()
        total_loss = 0

        for X_batch, y_batch in train_loader:
            X_batch = X_batch.to(device)
            y_batch = y_batch.to(device)

            optimizer.zero_grad()

            outputs = model(X_batch)
            loss = criterion(outputs, y_batch)

            loss.backward()
            optimizer.step()

            total_loss += loss.item()

        avg_train_loss = total_loss / len(train_loader)

        val_acc, val_prec, val_rec, val_f1, _, _, _ = evaluate_model(
            model,
            val_loader
        )

        history["train_loss"].append(avg_train_loss)
        history["val_accuracy"].append(val_acc)
        history["val_precision"].append(val_prec)
        history["val_recall"].append(val_rec)
        history["val_f1"].append(val_f1)

        print(
            f"Epoch {epoch}/{epochs} | "
            f"Loss: {avg_train_loss:.6f} | "
            f"Val Acc: {val_acc:.6f} | "
            f"Val Precision: {val_prec:.6f} | "
            f"Val Recall: {val_rec:.6f} | "
            f"Val F1: {val_f1:.6f}"
        )

    return model, history


# 12. Plot History

def plot_history(history, model_name):
    epochs_range = range(1, len(history["train_loss"]) + 1)

    plt.figure(figsize=(8, 5))
    plt.plot(epochs_range, history["train_loss"], marker="o")
    plt.title(f"{model_name} Training Loss")
    plt.xlabel("Epoch")
    plt.ylabel("Loss")
    plt.grid(True)
    plt.show()

    plt.figure(figsize=(8, 5))
    plt.plot(epochs_range, history["val_accuracy"], marker="o", label="Validation Accuracy")
    plt.plot(epochs_range, history["val_f1"], marker="o", label="Validation F1-score")
    plt.title(f"{model_name} Validation Accuracy and F1-score")
    plt.xlabel("Epoch")
    plt.ylabel("Score")
    plt.legend()
    plt.grid(True)
    plt.show()

# 13. Plot Confusion Matrix

def plot_confusion_matrix(cm, model_name):
    plt.figure(figsize=(6, 5))
    plt.imshow(cm)
    plt.title(f"Confusion Matrix - {model_name}")
    plt.xlabel("Predicted Label")
    plt.ylabel("Actual Label")

    class_names = ["True", "Fake"]
    plt.xticks([0, 1], class_names)
    plt.yticks([0, 1], class_names)

    for i in range(cm.shape[0]):
        for j in range(cm.shape[1]):
            plt.text(
                j,
                i,
                cm[i, j],
                ha="center",
                va="center"
            )

    plt.colorbar()
    plt.show()

# 14. Training CNN

EPOCHS = 5
LEARNING_RATE = 0.001
EMBED_DIM = 64

cnn_model = CNNTextClassifier(
    vocab_size=vocab_size,
    embed_dim=EMBED_DIM,
    num_filters=100,
    kernel_sizes=(3, 4, 5),
    dropout=0.5
)

cnn_model, cnn_history = train_model(
    model=cnn_model,
    model_name="CNN",
    train_loader=train_loader,
    val_loader=val_loader,
    epochs=EPOCHS,
    learning_rate=LEARNING_RATE
)

plot_history(cnn_history, "CNN")

# 15. Evaluasi CNN

cnn_acc, cnn_prec, cnn_rec, cnn_f1, cnn_cm, cnn_y_true, cnn_y_pred = evaluate_model(
    cnn_model,
    test_loader
)

print("\n===== CNN TEST RESULTS =====")
print(f"Accuracy : {cnn_acc * 100:.2f}")
print(f"Precision: {cnn_prec * 100:.2f}")
print(f"Recall   : {cnn_rec * 100:.2f}")
print(f"F1-score : {cnn_f1 * 100:.2f}")
print("Confusion Matrix:")
print(cnn_cm)

print("\nClassification Report - CNN")
print(classification_report(cnn_y_true, cnn_y_pred, target_names=["True", "Fake"]))

plot_confusion_matrix(cnn_cm, "CNN")

# 16. Training BiLSTM
bilstm_model = BiLSTMTextClassifier(
    vocab_size=vocab_size,
    embed_dim=EMBED_DIM,
    hidden_dim=128,
    num_layers=2,
    dropout=0.5
)

bilstm_model, bilstm_history = train_model(
    model=bilstm_model,
    model_name="BiLSTM",
    train_loader=train_loader,
    val_loader=val_loader,
    epochs=EPOCHS,
    learning_rate=LEARNING_RATE
)

plot_history(bilstm_history, "BiLSTM")

# 17. Evaluasi BiLSTM
bilstm_acc, bilstm_prec, bilstm_rec, bilstm_f1, bilstm_cm, bilstm_y_true, bilstm_y_pred = evaluate_model(
    bilstm_model,
    test_loader
)

print("\n===== BiLSTM TEST RESULTS =====")
print(f"Accuracy : {bilstm_acc * 100:.2f}")
print(f"Precision: {bilstm_prec * 100:.2f}")
print(f"Recall   : {bilstm_rec * 100:.2f}")
print(f"F1-score : {bilstm_f1 * 100:.2f}")
print("Confusion Matrix:")
print(bilstm_cm)

print("\nClassification Report - BiLSTM")
print(classification_report(bilstm_y_true, bilstm_y_pred, target_names=["True", "Fake"]))

plot_confusion_matrix(bilstm_cm, "BiLSTM")

# 18. Final Comparison Table
results = pd.DataFrame({
    "Model": ["CNN", "BiLSTM"],
    "Accuracy": [cnn_acc * 100, bilstm_acc * 100],
    "Precision": [cnn_prec * 100, bilstm_prec * 100],
    "Recall": [cnn_rec * 100, bilstm_rec * 100],
    "F1-score": [cnn_f1 * 100, bilstm_f1 * 100]
})

print("\n===== FINAL COMPARISON TABLE =====")
print(results.round(2))

# 19. Plot Final Comparison
x = np.arange(len(results["Model"]))
width = 0.35

plt.figure(figsize=(8, 5))
plt.bar(x - width/2, results["Accuracy"], width, label="Accuracy")
plt.bar(x + width/2, results["F1-score"], width, label="F1-score")

plt.xticks(x, results["Model"])
plt.ylabel("Score (%)")
plt.title("Accuracy and F1-score Comparison")
plt.legend()
plt.ylim(95, 100)
plt.grid(axis="y")
plt.show()

# 20. Save Model dan Result
torch.save(cnn_model.state_dict(), "cnn_fake_news_model_paper_like.pt")
torch.save(bilstm_model.state_dict(), "bilstm_fake_news_model_paper_like.pt")

results.to_csv("cnn_bilstm_results_paper_like.csv", index=False)